main: re.imc.geysermodelengine.GeyserModelEngine
name: GeyserModelEngine
version: '1.0.0'
api-version: '1.21'

authors:
  - zimzaza4
  - willem.dev

load: STARTUP

dependencies:
  server:
    GeyserUtils:
      required: true
    packetevents:
      required: true
    floodgate:
      required: true
    ModelEngine:
      required: false
      join-classpath: true
    BetterModel:
      required: false
      join-classpath: true